apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::215942507511:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1JC5T7ENGT637
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::215942507511:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-31T18:07:53Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "941"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ff548102-eb16-402a-8779-70c6affd0698
