apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::215942507511:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-PQI4BHN14J0V
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::215942507511:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-05-31T07:49:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "973"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: bcc4af9f-2b3e-4517-b25e-b03c60236972
